/**
 * AUTO-GENERATED - do not edit by hand.
 * Single source of truth is package.json "version". Regenerated by
 * scripts/write-version.mjs from the build scripts. To change the version, bump
 * package.json and rebuild (version.test.ts guards against drift).
 */
export const MCP_VERSION = '1.9.1';
