#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));

if (!pkg.version || typeof pkg.version !== 'string') {
  throw new Error('package.json version must be a string');
}

const output = `/**
 * AUTO-GENERATED - do not edit by hand.
 * Single source of truth is package.json "version". Regenerated by
 * scripts/write-version.mjs from the build scripts. To change the version, bump
 * package.json and rebuild (version.test.ts guards against drift).
 */
export const MCP_VERSION = '${pkg.version}';
`;
writeFileSync(resolve(root, 'src/lib/version.ts'), output, 'utf8');
